[build]
  publish = "dist"
  command = "npm ci && npm run build"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

# Environment variables (set these in Netlify dashboard)
# VITE_SUPABASE_URL
# VITE_SUPABASE_ANON_KEY
# SUPABASE_SERVICE_ROLE_KEY
# VITE_STRIPE_PUBLISHABLE_KEY
# STRIPE_SECRET_KEY
# VITE_STRIPE_PRICE_ID_MONTHLY
# VITE_STRIPE_PRICE_ID_YEARLY
# VITE_OPENAI_API_KEY
# VITE_APP_URL
# VITE_MONTHLY_PRICE
# VITE_YEARLY_PRICE
# VITE_TRIAL_DAYS
# STRIPE_WEBHOOK_SECRET